### ISSUE TITLE
Cannot Connect to firebase 

### ISSUE THREAD

**Issue by milannzz** [bhajan-limitless/shieldapp#5]
cannot connect firebase a the email used is not the public one @MukeshBahuguna this is your job.

**Comment by MukeshBahuguna** [comment]
> cannot connect firebase a the email used is not the public one @MukeshBahuguna this is your job.

what exactly is missing? @milannzz

**Comment by milannzz** [comment]
check the code man @MukeshBahuguna  ,i cannot run the app in my  machine :(
